wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/ValueLearningIRL/main_iql.py
    python_version: 3.9.6
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721744903.444757
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      - 35
      4: 3.9.6
      5: 0.16.2
      8:
      - 5
      13: darwin-arm64
